name: bloc_hero
description: Bloc from zero to hero project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_bloc: ^6.0.6
  equatable: ^1.2.5
  connectivity_plus: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^7.0.4

flutter:
  uses-material-design: true
